# Generated by Django 4.0.4 on 2022-10-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseId', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=500)),
                ('Coursetitle', models.CharField(max_length=500)),
                ('Frontcard', models.CharField(max_length=500)),
                ('Backcard', models.CharField(max_length=500)),
            ],
        ),
    ]
